### ISSUE TITLE
Add build for Python 3.8

### ISSUE THREAD

**Issue by ajoubertza** [tango-controls/boost-ci#2]
This package is used by PyTango for [Windows builds](https://github.com/tango-controls/pytango/blob/a783c63d222e2e78e4da67ecac0e5be451093bb2/appveyor.yml#L8), and we want PyTango to support Python 3.8.

Related issue: https://github.com/tango-controls/pytango/pull/344

**Comment by sdebionne** [comment]
Just wondering why not use the [conda-forge builds](https://anaconda.org/conda-forge/boost) instead? Is it because pyTango should be better linked against the static libraries or is there other reasons?

**Comment by ajoubertza** [comment]
@sdebionne The Windows native builds for PyTango are done [using AppVeyor](https://github.com/tango-controls/pytango/blob/4230204/appveyor.yml) in a non-Conda environment, so could we still use conda-forge?  Or are you thinking to move the AppVeyor build into a Conda environment somehow?
